import { useEffect, useRef, useState } from 'react';
import { Settings, ScanLine } from 'lucide-react';
import { browser } from 'wxt/browser';
import { activeTab, explainError } from '../../lib/browser';
import { defaultFormFillerPreferences, loadFormFillerPreferences, saveFormFillerPreferences, type FormFillerPreferences } from './preferences';

type Report = { filled: number; ignored: number; failed: number; message?: string };
export function FormFillerTool() {
  const [prefs, setPrefs] = useState<FormFillerPreferences>(defaultFormFillerPreferences); const [ready, setReady] = useState(false); const [status, setStatus] = useState(''); const [report, setReport] = useState<Report | null>(null); const [settings, setSettings] = useState(false); const [showPassword, setShowPassword] = useState(false); const generation = useRef(0);
  useEffect(() => { void loadFormFillerPreferences().then(value => { setPrefs(value); setReady(true); }).catch(error => setStatus(explainError(error))); }, []);
  async function choose() { const current = ++generation.current; setReport(null); try { const tab = await activeTab(); const [injection] = await browser.scripting.executeScript({ target: { tabId: tab.id }, files: ['/form-filler.js' as never] }); if (!injection?.documentId) throw new Error('Il documento non è più disponibile. Riprova.'); const [response] = await browser.tabs.sendMessage(tab.id, { type: 'swiss-form-filler-start', preferences: prefs }, { documentId: injection.documentId }); if (current !== generation.current) return; if (!response?.ok) throw new Error(response?.error || 'Il selettore non è disponibile.'); setStatus('Punta un contenitore e clicca. ↑ amplia, ↓ restringe, Invio conferma, Esc annulla.'); } catch (error) { if (current === generation.current) setStatus(explainError(error)); } }
  useEffect(() => { const listener = (message: unknown) => { const data = message as { type?: string; report?: Report; error?: string }; if (data.type === 'swiss-form-filler-report') { setReport(data.report || null); setStatus(data.report?.message || 'Compilazione completata.'); } if (data.type === 'swiss-form-filler-cancelled') setStatus('Selezione annullata.'); if (data.type === 'swiss-form-filler-error') setStatus(data.error || 'Compilazione non riuscita.'); }; browser.runtime.onMessage.addListener(listener); return () => browser.runtime.onMessage.removeListener(listener); }, []);
  async function persist(next: FormFillerPreferences) { setPrefs(next); try { await saveFormFillerPreferences(next); } catch (error) { setStatus(explainError(error)); } }
  return <section><div className="section-heading"><h2>Compila form</h2><button className="icon-button" aria-label="Impostazioni compilazione form" onClick={() => setSettings(true)}><Settings /></button></div><p className="muted">Genera dati fittizi realistici nel contenitore che scegli. I moduli non vengono inviati.</p><label htmlFor="form-locale">Lingua dei dati</label><select id="form-locale" disabled={!ready} value={prefs.locale} onChange={event => void persist({ ...prefs, locale: event.target.value as 'en' | 'it' })}><option value="en">English</option><option value="it">Italiano</option></select><div className="tool-actions"><button disabled={!ready} onClick={() => void choose()}><ScanLine aria-hidden="true" /> Seleziona elemento</button></div><p role="status" className="status">{status}</p>{report && <p className="notice">Compilati: {report.filled}. Ignorati: {report.ignored}. Non compilati: {report.failed}.</p>}{settings && <div className="dialog-backdrop" role="presentation"><section role="dialog" aria-modal="true" aria-labelledby="form-settings-title" className="tool-dialog"><div className="section-heading"><h3 id="form-settings-title">Impostazioni compilazione</h3><button onClick={() => setSettings(false)}>Chiudi</button></div><label htmlFor="fill-password">Password prefissata</label><div className="password-row"><input id="fill-password" type={showPassword ? 'text' : 'password'} value={prefs.password} onChange={event => void persist({ ...prefs, password: event.target.value })} /><button onClick={() => setShowPassword(value => !value)}>{showPassword ? 'Nascondi' : 'Mostra'}</button></div><p className="muted">Se vuota, viene generata una password di 16 caratteri per ogni form.</p><label htmlFor="ignored-fields">Campi da ignorare</label><input id="ignored-fields" value={prefs.ignored} onChange={event => void persist({ ...prefs, ignored: event.target.value })} /><label className="check-label"><input type="checkbox" checked={prefs.preserveExisting} onChange={event => void persist({ ...prefs, preserveExisting: event.target.checked })} /> Ignora campi già compilati</label></section></div>}</section>;
}
